added movie components
juliendubrail/cineflix pull request #1
Opened 2019-03-16 12:15 UTC by juliendubrail

2019-03-17 17:08 UTC, fredpinon commented on src/components/MovieList.js
> +                poster={movies[i].poster_path}
.map loop sur la movies array et te donne access a chaque `movie` object. Donc pas besoin d'utiliser `i` pour acceder au `title` et `poster_path`. Tu peux faire: 
`<MovieCard name={movie.title} poster={movie.poster_path} />`
ou encore mieux: 
```
 {movies.map(({ title, poster_path }) => {
          return (
            <div className="col-md-4" style={{ marginBottom: "2rem" }}>
              <MovieCard name={title} poster={poster_path} />
            </div>
          );
        })}
```
et comme React veux une unique key prop pour chaque element d'une liste tu peux choper l'id du movie. J'ai aussi enlever le explicit return et renomer `name` pour `title` (qu'il faudra du coup renommer dans `MovieCard`): 
```
 {movies.map(({ title, poster_path, id }) => (
          <div className="col-md-4" key={id} style={{ marginBottom: "2rem" }}>
            <MovieCard title={title} poster={poster_path} />
          </div>
  ))}
```

2019-03-17 17:08 UTC, fredpinon commented on src/components/MovieCard.js
> +  );
Tu peux enlever le id comme tu ne l'utilise pas ici. 

Et comme tu as eu besoin du `div` uniquement parce que tu ne peux return plus d'un element tu peux utiliser les fragments: 

```
const MovieCard = ({ name, poster }) => (
  <>
    <img alt="movies" src={`https://image.tmdb.org/t/p/w300/${poster}`} />
    <p className="movie_title">{name}</p>
  </>
);
```

2019-03-17 17:08 UTC, fredpinon commented on src/containers/App.js
> +  }
il y a pas mal de duplication ici. Tu pourrais créer un fichier: `src/utils.js` dans lequel tu aurais une fonction `baseFetch` qui recoit l'url et return la data ou l'error. Pour le moment on fais pas de error handling mais c'est pas grave: 

```
const myFetch = url =>
  fetch(url)
    .then(response => response.json())
    .then(data => data)
    .catch(error => error);
```
puis: 
```
async componentDidMount() {
    try {
      const recommendedMovies = await myFetch(RECOMENDATIONS);
      const actionMovies = await myFetch(ACTION_MOVIES);
      this.setState({
        recommendedMovies,
        actionMovies
      });
    } catch (e) {
      console.log(e);
    }
  }
```
ca fait que si `myFetch` fail pour une des categorie de movies, le state sera `undefined` pour cette categorie. Donc il faut rajouter des check avant de render `<MovieList/>` avec `movies` prop qui pourrait etre = a `undefined` vs une array (si `movies===undefined` movies.map causera un crash)

2019-03-17 17:08 UTC, fredpinon commented on src/containers/App.js
> +        <MovieList category={`ACTION`} movies={action} />
Par rapport au commentaire plus haut
```
{recommendedMovies && (
      <MovieList category={`DISCOVER`} movies={recommendedMovies} />
)}
{actionMovies && (
      <MovieList category={`ACTION`} movies={actionMovies} />
)}
```

comme ca si `recommendedMovies` ou `actionMovies` et undefined, la `MovieList` sera pas rendered pour cette array

2019-03-17 17:08 UTC, fredpinon commented on src/containers/App.js
> +  };
je changerais le state pour 
```
state = {
    recommendedMovies: null,
    actionMovies: null,
    searchInput: ""
  };
```

2019-03-20 13:03 UTC, fredpinon requested changes

2019-03-20 13:03 UTC, fredpinon commented on src/containers/App.js
> +    try {
il faut just monter le `try {` au dessus des `await` car l'idee de try c que une erreur causée par du code dans un try block sera accessible dans le catch block, et ici les erreur peuvent etre causée par le fetch call (dans getData)

2019-03-20 13:03 UTC, fredpinon commented on src/utils/fetch.js
> +
utilise cette version: 
```
const getData = url =>
  fetch(url)
    .then(response => response.json())
    .then(data => data)
    .catch(error => error);
```
ou alors rajoute un return devant le `fetch(url)` sur la version que tu as commented out.

2019-03-20 14:05 UTC, juliendubrail commented on src/containers/App.js
> +    try {
je l'avais descendus pour tester.

2019-03-20 14:06 UTC, juliendubrail commented on src/utils/fetch.js
> +
en retirant les brackets ca marche

2019-03-20 20:26 UTC, merged