search feature
juliendubrail/cineflix pull request #2
Opened 2019-03-20 22:52 UTC by juliendubrail

2019-03-23 10:36 UTC, fredpinon requested changes
ZBRA! l'idee du dynamic search c que ca cherche dans l'api a chaque fois que le user tap une lettre dans la search bar, donc pas besoin de search button, ca search a chaque key press, pas quand le user press search. Pour le moment tu filtre parmi les films que tu as dans les deux categories que tu fetch au debut, mais il y a en a bien plus dans l'api qui pourraient faire partie des resultats de recherche. J'ai mis quelques commentaires par rapport au SearchBar que tu peux address et merge, puis pour la search feature je pense que le mieux c que tu recommence (apres avoir merge les changements) en suivant ces steps la: 

- capter les key press: tu peux rajouter un onKeyUp prop sur le <input/> element et appeler un callback qui est definie dans App. 
- dans ce callback tu appel getData en lui passant cet url `https://movied.herokuapp.com/search?q=${e.target.value}`
- tu saves ce que tu recoi sur une nouvelle prop sur le state de App: searchResults (initialement null)
- dans render de App, render un MovieList component avec category "SEARCH RESULTS" en lui passant les searchResults sur la `movies` prop. La condition pour les render est la meme que les deux autre listes. Les search results doivent apparaitre au debut de la page donc place cette liste just au dessous de 
```
<SearchBar
          value={this.state.searchInput}
          onInputChange={this.onInputChange}
        />
```
Une fois que t'a fais ca on pourra voir si ca vaut le coup d'optimiser quelques trucs:
- peut etre optimiser la search avec throttle ou je sais pas quoi
- voir si les component render pas trop etc
- utiliser le render prop patter sur le MovieList component

2019-03-23 10:36 UTC, fredpinon commented on src/components/SearchBar.js
> +const SearchBar = ({onInputChange}) => {
ce component est compliqué a lire parce qui'il y a beaucoup de jsx et bcp de class. C'est pas vraiment une SearchBar mais une App bar comme ca comprend le nom de l'app, de la navigation et le search. Je pense que tu pourrais avoir un component AppBar, qui render trois components: Title, Nav, Search qui seraient definies dans d'autres files. Check bien aussi que tu as besoin de toutes ces class (j'y connais rien en css 🤷🏻‍♂️) et check la console qui me montre ce warning "index.js:1446 Warning: Invalid DOM property `class`. Did you mean `className`?"

2019-03-23 10:36 UTC, fredpinon commented on src/containers/App.js
> +  }
quand tu ouvre une review enleve les console.logs. tu peux changer ca pour 

```
onInputChange = event => this.setState({ searchInput: event.target.value });
```

2019-03-23 10:36 UTC, fredpinon commented on src/containers/App.js
> +    }
tout ce bloque peut etre retirer (ligne 35 a 46) par ce qu'on va faire le search autrement

2019-03-23 10:36 UTC, fredpinon commented on src/containers/App.js
> +        <SearchBar   value={this.state.searchInput} onInputChange={this.onInputChange} />
comme tu destructure deja `searchInput` du state ligne 34 tu peux le passer direct a la `value` prop
```
<SearchBar   value={searchInput} onInputChange={this.onInputChange} />
```

2019-03-27 09:48 UTC, juliendubrail commented on src/components/SearchBar.js
> +const SearchBar = ({onInputChange}) => {
oui, les classname c'est du à bootstrap.

2019-04-01 21:53 UTC, fredpinon reviewed
Je pense qu'apres avoir fait les petite modif tu peux merge dans master. Ensuite tu pourrais utiliser la search bar dans la nav bar comme c pas encore le cas. Puis commencer les error handling: 
* error handling: montrer un message si il y a une fetch error.
* no results found: montrer un message si il n’y a pas de résultats pour cette recherche

2019-04-01 21:53 UTC, fredpinon commented on src/containers/App.js
> +}
je changerais juste onInputChange pour: (et en rajoutant resetResults sur la class)
```
resetResults = () => this.setState({ searchResults: null });

  onInputChange = event => {
    this.setState(
      {
        searchInput: event.target.value
      },
      () => {
        const shouldSearch = this.state.searchInput.length > 1;
        return shouldSearch ? this.getInfo() : this.resetResults();
      }
    );
  };
```

comme ca tu te debarasse des resultats quand tu efface le search input (tu devrais aussi appeler resetResults quand la petit crois du search input est cliquée). Le `shouldSearch` peut paraitre overkill mais c'est bien de montrer tes intentions dans ton code via des nom descriptifs (y a une just milieu a trouver mais la ct plutot approprié), comme ca les gens qui te lise ou quand tu te lira plus tard ce que tu voulais faire sera clair sans avoir vraiment besoin de lire la logique

2019-04-01 21:53 UTC, fredpinon commented on src/containers/App.js
> +    } */
enleve ce commentaire

2019-04-01 21:53 UTC, fredpinon commented on src/containers/App.js
> +} */
enleve ce commentaire

2019-04-02 09:29 UTC, merged